# Site settings
title: 훈석의 블로그

author:
  name: '정훈석'
  email: gnstjr2000@gmail.com
  github_username:  HunSeokJeong


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
